### PR TITLE
(Bug Fixed!)JENKINS-28709 Join Plugin ignores dependencies wrapped with flexible-…

### PR DESCRIPTION
**Pull request by Edgar0119**
Fix bug [JENKINS-28709](https://issues.jenkins-ci.org/browse/JENKINS-28709)
Now it can handle "hudson.plugins.parameterizedtrigger.BuildTrigger"  in Flexible publisher!

### CODE REVIEW

**Comment by mdonohue** [comment]
This is much more readable - thank you for fixing the whitespace.

I have two more suggestions here:
1. The Flexible Publisher should be an optional dependency
2. Can you explain how the code behaves if the flexible publisher plugin is not installed?

**Comment by Edgar0119** [comment]
Hello,
Flexible Publisher plugin cannot be an optional dependency, 
It just like the join-plugin has dependency on [parameterized-trigger](https://wiki.jenkins-ci.org/display/JENKINS/Parameterized+Trigger+Plugin), like this (original code)line https://github.com/jenkinsci/join-plugin/pull/10/files#diff-e6e42dd5529efb392db38cf6e0030c29R265
The join-plugin was support parameterized-trigger plugin, so that join-plugin dependency on parameterized-trigger,and if the join-plugin work without parameterized-trigger, that will be crash.
Similarly, the join-plugin has dependency on Flexible Publisher plugin.

**Comment by mdonohue** [comment]
I just tried this with a fresh jenkins 1.600 install, no parameterized trigger, no flexible publisher - the published 1.19 version of the join plugin works fine.  I can setup a simple join scheme and it runs as expected.

With the current pull request, the join plugin won't even install.  It is rejected because the 'flexible-publisher' dependency isn't marked as optional.     

Please make it optional, and test on a jenkins install without the flexible publisher.  The join plugin should continue to operate as it did before.    If you look carefully at how the parameterized trigger code works, it uses runtime lookups, to make sure the presence of the plugin is not required.

**Comment by Edgar0119** [comment]
I'm sorry , I misunderstood what you mean , but now I understand.

I will let flexible publisher be an optional dependency, and I'll ensure join plugin work correctly without flexible publisher installed.

Thank you for your patience and suggestions .

**Comment by mdonohue** [comment]
Thanks for the fixes!

**Pull request merged**
